compensation:
   db:
      driver :  com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.0.101:3306/tcc?useUnicode=true&amp;characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
